/**
 * Performance primitives (P3).
 *
 * Reusable, behaviour-neutral foundations for keeping CleanOps fast as data
 * grows. All pieces are source-agnostic and remain valid after the future
 * Supabase operational-data migration.
 */
export { perf } from "./instrumentation";
export {
  IntervalCache,
  buildIntervalCacheKey,
  referenceToken,
  type IntervalCacheKeyParts,
  type IntervalCacheOptions,
} from "./intervalCache";
export {
  createLookupSelector,
  createByIdSelector,
  createFieldByIdSelector,
} from "./selectors";
export {
  PERFORMANCE_BUDGETS,
  getPerformanceBudget,
  checkBudget,
  type PerformanceBudget,
  type BudgetCheck,
} from "./budget";
export {
  buildBudgetReport,
  type BudgetGrade,
  type BudgetDimensionResult,
  type BudgetReportRow,
} from "./budgetReport";
export type {
  MetricFamily,
  UsageMetricKind,
  UsageEvent,
  UsageAggregate,
  UsageMeter,
} from "./metering.blueprint";
export {
  OPERATIONAL_SURFACES,
  AI_FEATURE_RISKS,
  type OperationalSurface,
  type OperationalDataSource,
  type GrowthRisk,
  type MonitoringStatus,
  type ScalingDimension,
  type AiFeatureRisk,
} from "./operationalMonitoring";
export {
  ACTIVITY_EVENT_COLUMNS,
  ACTIVITY_QUERY_PATTERNS,
  EMPLOYEE_ACTIVITY_RECOMMENDATION,
  EMPLOYEE_ACTIVITY_SOURCES,
  RETENTION_CLASSES,
  ACTIVITY_METERING_COUNTERS,
  type ActivityEventColumn,
  type ActivityQueryPattern,
  type ActivityQueryRequest,
  type ActivitySeverity,
  type EmployeeActivitySource,
  type RetentionClass,
} from "./activityLog.blueprint";
export {
  SCHEDULE_DEPENDENCIES,
  SCHEDULE_DETAIL_ONLY,
  SCHEDULE_SCALING,
  SCHEDULE_SUMMARY_FIELDS,
  SCHEDULE_QUERY_INDEXES,
  SCHEDULE_INVALIDATION_RULES,
  SCHEDULE_REALTIME_EVENTS,
  SCHEDULE_METERING_COUNTERS,
  SCHEDULE_RISKS,
  type ScheduleDependency,
  type ScheduleScalingScenario,
  type ScheduleScalingGrade,
  type ScheduleSummaryField,
  type ScheduleQueryRequest,
  type ScheduleQueryResponse,
  type ScheduleInvalidationRule,
  type ScheduleInvalidationScope,
  type ScheduleRealtimeEvent,
  type ScheduleRealtimeClass,
  type ScheduleRisk,
} from "./schedule.blueprint";
export {
  HYDRATION_MAP,
  DATA_TIERS,
  STARTUP_BUDGETS,
  CONTEXT_RESPONSIBILITIES,
  LOADING_FLOWS,
  COMPANY_SCOPE_FINDINGS,
  CACHE_OWNERS,
  MIGRATION_READINESS,
  HYDRATION_RISKS,
  type HydrationEntry,
  type HydrationSource,
  type HydrationTiming,
  type HydrationScope,
  type HydrationGrowth,
  type DataTier,
  type DataTierDefinition,
  type StartupBudget,
  type ContextDestination,
  type ContextResponsibility,
  type LoadingFlow,
  type CompanyScopeFinding,
  type CacheOwner,
  type MigrationPriority,
  type MigrationReadinessRow,
  type HydrationRisk,
} from "./hydration.blueprint";
export {
  MIGRATION_LAYERS,
  APPCONTEXT_RESPONSIBILITY,
  APPCONTEXT_EXTRACTION_PLAN,
  COMPANY_PROVIDER,
  QUERY_LAYER_CAPABILITIES,
  ENTITY_MIGRATIONS,
  SUMMARY_DETAIL_CONTRACTS,
  INDEX_STRATEGY,
  CACHE_LAYERS,
  REALTIME_EVENTS,
  REALTIME_CHANNEL_STRATEGY,
  METERING_HOOKS,
  MIGRATION_WAVES,
  WAVE_RISKS,
  type ArchitectureLayer,
  type AppContextResponsibility,
  type CompanyProviderSpec,
  type QueryCapability,
  type EntityMigration,
  type WaveId,
  type SummaryDetailContract,
  type IndexRecommendation,
  type CacheLayerSpec,
  type RealtimeClass,
  type RealtimeEventSpec,
  type MeteringHookSpec,
  type MigrationWave,
  type WaveRisk,
  type WaveRiskLevel,
} from "./migration.blueprint";
export {
  PARITY_RESULTS,
  CONTRACT_COMPLETENESS,
  DTO_REVIEW,
  SURFACE_READINESS,
  WAVE1_TABLES,
  PRE_WAVE1_RISKS,
  WAVE1_RECOMMENDATION,
  type ParityOutcome,
  type ParityValidationResult,
  type ContractStatus,
  type ContractCompleteness,
  type DtoFieldVerdict,
  type DtoFieldReview,
  type SurfaceReadiness,
  type TableProposal,
  type RiskLevel,
  type PreWaveRisk,
  type Wave1Option,
  type Wave1Recommendation,
} from "./wave1.readiness.blueprint";
export {
  SOAK_FLAGS,
  SOAK_WORKFLOWS,
  SOAK_SIGNALS,
  CUTOVER_CRITERIA,
  SOAK_READINESS,
  type SoakFlagConfig,
  type SoakWorkflowSpec,
  type SoakSignal,
  type SoakSignalSeverity,
  type CutoverCriterion,
  type SoakVerdict,
  type SoakReadiness,
} from "./wave1e.soak.blueprint";
export {
  PRE_CUTOVER_CHECKLIST,
  AUTHORITY_MODEL,
  WRITE_STRATEGY,
  READ_FALLBACK_POLICY,
  DIVERGENCE_HANDLING,
  ROLLBACK_PLAN,
  CUTOVER_EXIT_CRITERIA,
  CUSTOMER_MIGRATION_FINAL_STATUS,
  type CutoverCheck,
  type AuthoritySource,
  type AuthorityRow,
  type WriteStrategy,
  type WriteStrategyDecision,
  type FallbackRule,
  type DivergenceSeverity,
  type DivergenceRule,
  type RollbackStep,
  type CutoverExitCriterion,
  type CustomerMigrationStatus,
  type CustomerMigrationFinalStatus,
} from "./wave1f.cutover.blueprint";
export {
  CUSTOMER_FLAG_AUDIT,
  CUSTOMER_DATA_SOURCE_MAP,
  HIDDEN_DEPENDENCY_AUDIT,
  ROLLBACK_DRILL,
  MONITORING_AUDIT,
  LIVE_STAGING_CHECKLIST,
  KEEP_TEMPORARILY,
  FUTURE_CLEANUP_CANDIDATES,
  CUSTOMER_CLOSURE_AUDIT,
  type FlagEnv,
  type CustomerFlagAudit,
  type DataSourceKind,
  type CustomerDataSource,
  type DependencyClass,
  type DependencyOccurrence,
  type RollbackDrillStep,
  type MonitoringSignal,
  type RolloutStep,
  type CleanupItem,
  type ClosureVerdict,
  type CustomerClosureAudit,
} from "./wave1.closure.blueprint";
export {
  WORK_ORDER_MODEL,
  WORK_ORDER_READ_PATHS,
  WORK_ORDER_WRITE_PATHS,
  SCHEDULE_FIELD_DEPENDENCIES,
  CONTRACT_PROPOSALS,
  WORK_ORDER_TABLES,
  DEFERRED_TABLES,
  JSONB_STRATEGY,
  WORK_ORDER_WAVES,
  WORK_ORDER_RISKS,
  WORK_ORDER_DESIGN_VERDICT,
  type FieldClass,
  type ModelField,
  type ReadShape,
  type ReadPath,
  type WritePath,
  type ScheduleFieldDependency,
  type ContractProposal,
  type WorkOrderTableProposal,
  type JsonbVerdict,
  type JsonbDecision,
  type WorkOrderWave,
  type WorkOrderRisk,
  type WorkOrderDesignVerdict,
} from "./workorders.blueprint";
export {
  WO_SOAK_FLAGS,
  WO_SOAK_WORKFLOWS,
  WO_SOAK_SIGNALS,
  WO_CUTOVER_CRITERIA,
  WO_SOAK_LIMITATIONS,
  WO_SOAK_READINESS,
  type WorkOrderSoakFlagConfig,
  type WorkOrderSoakWorkflowSpec,
  type WorkOrderSoakSignal,
  type WorkOrderSoakSignalSeverity,
  type WorkOrderCutoverCriterion,
  type WorkOrderSoakLimitation,
  type WorkOrderSoakVerdict,
  type WorkOrderSoakReadiness,
} from "./workorders.soak.blueprint";
export {
  WO_PRE_CUTOVER_CHECKLIST,
  WO_AUTHORITY_MODEL,
  WO_WRITE_STRATEGY,
  WO_READ_FALLBACK_POLICY,
  WO_DIVERGENCE_HANDLING,
  WO_ROLLBACK_PLAN,
  WO_CUTOVER_EXIT_CRITERIA,
  WORK_ORDER_MIGRATION_FINAL_STATUS,
  type WorkOrderCutoverCheck,
  type WorkOrderAuthoritySource,
  type WorkOrderAuthorityRow,
  type WorkOrderWriteStrategy,
  type WorkOrderWriteStrategyDecision,
  type WorkOrderFallbackRule,
  type WorkOrderDivergenceSeverity,
  type WorkOrderDivergenceRule,
  type WorkOrderRollbackStep,
  type WorkOrderCutoverExitCriterion,
  type WorkOrderMigrationStatus,
  type WorkOrderMigrationFinalStatus,
} from "./workorders.cutover.blueprint";
export {
  SCHEDULE_INPUT_AUDIT,
  SCHEDULE_CONTRACT_DECISION,
  SCHEDULE_INPUT_BUILDERS,
  SCHEDULE_FETCH_CLASSES,
  SCHEDULE_SCAN_WIDENING_NOTE,
  SCHEDULE_CACHE_KEY_PARTS,
  SCHEDULE_CACHE_INVALIDATION,
  SCHEDULE_SHADOW_DIMENSIONS,
  SCHEDULE_SHADOW_ENTRYPOINTS,
  SCHEDULE_DESIGN_RISKS,
  SCHEDULE_MIGRATION_DESIGN_VERDICT,
  type ScheduleInputMigrationState,
  type ScheduleInputAuditRow,
  type ScheduleContractDecision,
  type ScheduleContractField,
  type ScheduleBuilderContract,
  type ScheduleFetchClass,
  type ScheduleCacheKeyPart,
  type ScheduleCacheInvalidation,
  type ScheduleShadowDimension,
  type ScheduleDesignRiskSeverity,
  type ScheduleDesignRisk,
  type ScheduleMigrationDesignStatus,
  type ScheduleMigrationDesignVerdict,
} from "./schedule.interval.blueprint";
export {
  SCHEDULE_FLAG_AUDIT,
  SCHEDULE_SOURCE_MAP,
  SCHEDULE_FALLBACK_PATH,
  SCHEDULE_SHADOW_SUMMARY,
  SCHEDULE_CACHE_BEHAVIOUR,
  SCHEDULE_MONITORING_AUDIT,
  SCHEDULE_ROLLBACK_DRILL,
  SCHEDULE_KEEP_TEMPORARILY,
  SCHEDULE_FUTURE_CLEANUP_CANDIDATES,
  SCHEDULE_CLOSURE_AUDIT,
  type ScheduleFlagEnv,
  type ScheduleFlagAudit,
  type ScheduleSourceKind,
  type ScheduleSourceRow,
  type ScheduleFallbackRow,
  type ScheduleShadowSummaryRow,
  type ScheduleCacheBehaviourRow,
  type ScheduleMonitoringSignal,
  type ScheduleRollbackStep,
  type ScheduleCleanupItem,
  type ScheduleClosureVerdict,
  type ScheduleClosureAudit,
} from "./schedule.closure.blueprint";
export {
  EMPLOYEE_MODEL,
  EMPLOYEE_READ_PATHS,
  EMPLOYEE_WRITE_PATHS,
  EMPLOYEE_SCHEDULE_DEPENDENCIES,
  EMPLOYEE_DEPENDENCY_AUDIT,
  EMPLOYEE_CONTRACT_PROPOSALS,
  EMPLOYEE_EMP0_PARITY,
  EMPLOYEE_EMP1_DELIVERABLES,
  EMPLOYEE_TABLES,
  EMPLOYEE_DEFERRED_TABLES,
  EMPLOYEE_JSONB_STRATEGY,
  EMPLOYEE_WAVES,
  EMPLOYEE_RISKS,
  EMPLOYEE_DESIGN_VERDICT,
  type EmployeeFieldClass,
  type EmployeeModelField,
  type EmployeeReadShape,
  type EmployeeReadPath,
  type EmployeeWritePath,
  type EmployeeScheduleDependency,
  type EmployeeDependencyDisposition,
  type EmployeeDependencyRow,
  type EmployeeContractProposal,
  type EmployeeParityVerdict,
  type EmployeeParityDimension,
  type EmployeeEmp1Verdict,
  type EmployeeEmp1Deliverable,
  type EmployeeTableProposal,
  type EmployeeJsonbVerdict,
  type EmployeeJsonbDecision,
  type EmployeeWave,
  type EmployeeRisk,
  type EmployeeDesignVerdict,
} from "./employees.blueprint";
